apiVersion: batch/v1
kind: Job
metadata:
  name: burst-publisher
  namespace: openchat-dev
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: burst
          image: openchat/burst-publisher:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: COUNT
              value: "500"
            - name: COUNTRY
              value: "IE"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
