apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ea-k3d
servers: 1
agents: 2
image: rancher/k3s:v1.34.2-k3s1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
